### ISSUE TITLE
Add year indication into sequence JSON spec

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#54]
In order to simplify the operation of filling up a table with semesters from the data, I would like to change the sequence JSON spec once again to look something like:

```json
yearList: [
    {
        "fall": { semesterObject1 },
        "winter": { semesterObject2 },
        "summer": { semesterObject3 }
    },
    {
        "fall": { semesterObject4 },
        "winter": { semesterObject5 },
        "summer": { semesterObject6 }
    },
    etc
]
```

**Comment by Davidster** [comment]
I'll make this change by editing the webscraping code contained in `/webscraping/node/course-seq-scraper/`

**Comment by Davidster** [comment]
Development done on branch [addYearsToSequenceJson-54](/stumash/CoursePlanner/tree/addYearsToSequenceJson-54)

**Comment by stumash** [comment]
This issue was resolved by merging #57 into branch [frontendRework-45](/stumash/CoursePlanner/tree/frontendRework-45).  However, since the Github feature of issue-closing-by-PR only works when merging onto the repo's default branch (in this case [master](/stumash/CoursePlanner/tree/master)), this issue had to be closed manually.

**Comment by Davidster** [comment]
wackkkkkkk

**Comment by stumash** [comment]
It's honestly pretty sensible when you think about it.  More wack is making major breaking changes to the code such as being in the middle of complete backend cleanup and frontend re-write and not merging it all onto master.
